### ISSUE TITLE
sprites css width and height are different with original images

### ISSUE THREAD

**Issue by ihaolin** [sprity/sprity#15]
Hello，
I have 3 images, two are 20×20，one is 40×40，but when I use bellow configuration to generate the css isn't different width and height:

Configuration:

```javascript
gulp.task('sprites', function () {
    return sprity.src({
        src: 'images/**/*.png',
        name: 'icons',
        style: './icons.css',
        processor: 'css',
        prefix: 'wm'
    })
    .pipe(imagemin())
    .pipe(gulpif('*.png', gulp.dest('./dist/images/'), gulp.dest('./dist/css/')))
});
```
But the generated css is:

```css
.wm {
  background-image: url("../images/icons.png");
}
.wm-star-off {
  background-position: -0px -0px;
  width: 28px;  //Shouldn't be 20px?
  height: 28px;
}
.wm-star-on {
  background-position: -0px -28px;
  width: 28px;
  height: 28px;
}
.wm-gotop {
  background-position: -0px -56px;
  width: 48px;
  height: 48px;
}
```
And, another issue is why not support one class, like this:
```css
.wm-star-off {
  background-image: url("../images/icons.png");
  background-position: -0px -0px;
  width: 28px;
  height: 28px;
}
.wm-star-on {
  background-image: url("../images/icons.png");
  background-position: -0px -28px;
  width: 28px;
  height: 28px;
}
.wm-gotop {
  background-image: url("../images/icons.png");
  background-position: -0px -56px;
  width: 48px;
  height: 48px;
}
```
