### ISSUE TITLE
Running sprity on multiple merged streams causes issues

### ISSUE THREAD

**Issue by jahan-addison** [sprity/sprity#63]
Hi, i am using node `4.4.4` with `sprity-lwip` and gulp.
I have the following gulp file:

``` javascript
const gulp     = require('gulp');
const gulpif   = require('gulp-if')
const merge    = require('merge2');
const sprity   = require('sprity');

gulp.task('sprites', function () {
  const images = {
    a: './images/a/*.png',
    b: './images/b/*.png',
    c: './images/c/*.png',
    };
  return merge(Object.keys(images).map(e => {
    return sprity.src({
      name:  e,
      src: images[e],
      out: './dist/images',
      style: e + '-sprite.scss',
      processor: 'sass',
      orientation: 'binary-tree',
    })
    .pipe(gulpif('*.png', gulp.dest('./dist/img/'), gulp.dest('./dist/css/')))
  }));
});
```

This creates `dist/img` with `dist/img/a`, `dist/img/b`, `dist/img/c` and similar with `dist/css`. The sprite image files themselves are fine.
However, the css merges together the different variables, as if not separating the context even though these are obviously different instances.

Each of `a-sprite.scss`, `b-sprite.scss`, and `c-sprite.scss` contains: 

``` scss
$img1-b: -0px -0px 75px 66px;
$img2-b: -75px -0px 75px 66px;
$img1-c: -0px -0px 75px 66px;
$img2-c: -75px -0px 75px 66px;
$img1-a: -0px -0px 75px 66px;
$img2-a: -75px -0px 75px 66px;
@mixin sprite-width($sprite) {
  width: nth($sprite, 3);
}
@mixin sprite-height($sprite) {
  height: nth($sprite, 4);
}
@function sprite-width($sprite) {
   @return nth($sprite, 3);
}
@function sprite-height($sprite) {
   @return nth($sprite, 4);
}
@mixin sprite-position($sprite) {
  $sprite-offset-x: nth($sprite, 1);
  $sprite-offset-y: nth($sprite, 2);
  background-position: $sprite-offset-x $sprite-offset-y;
}
@mixin sprite($sprite, $display: block) {
   @include sprite-position($sprite);
  background-repeat: no-repeat;
  overflow: hidden;
  display: $display;
  @include sprite-width($sprite);
  @include sprite-height($sprite);
}

.icon {
  background-image: url('../images/b.png');
}

.icon {
  background-image: url('../images/c.png');
}

.icon {
  background-image: url('../images/a.png');
}
```

There is _NO_ difference between each generated scss file. The older css-sprite module dealt with this correctly, and I dont see a reason why it'd do this now. I understand i could use the `split` option however i have different options that go to sprity (e.g. retina vs non retina etc) from a separate configuration.

In my actual production example where I map over a much larger list some scss files contain more combined than others, and then some all of the combined.
